# Generated by Django 4.0.6 on 2023-09-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес,г')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('composition', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Ассортимент на Бульваре',
            },
        ),
        migrations.CreateModel(
            name='Product_C',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес,г')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('composition', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Ассортимент на Черёмушках',
            },
        ),
        migrations.CreateModel(
            name='Product_K',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('weight', models.PositiveIntegerField(verbose_name='Вес,г')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('composition', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Позиция',
                'verbose_name_plural': 'Ассортимент на Краснознаменской',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
